# TODO: move to theme repo
name: Setup repo, Python and pipenv
description: Setup repo, Python and pipenv
inputs:
  command:
    required: false
    description: What command to pass to pipenv run
    default: ""
  python:
    required: false
    description: Version of Python to install
    default: "3.7"
  pipenv:
    required: false
    description: Either skip-lock or deploy
    default: "deploy"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        # require history to get back to last tag for version number of branches
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python }}

    - if: inputs.pipenv == 'skip-lock'
      # Use a non-editable install to make and install a wheel rather than link the src
      shell: bash
      run: sed -i 's/editable *= *true/editable = false/' Pipfile

    - if: inputs.command
      shell: bash
      run: |
        pip install pipenv
        pipenv install --dev --${{ inputs.pipenv }} --python $(python -c 'import sys; print(sys.executable)') && pipenv graph

    - if: inputs.command
      shell: bash
      run: pipenv run ${{ inputs.command }}
