# Changes here will be overwritten by Copier
_commit: 2.3.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: tom.cobb@diamond.ac.uk
author_name: Tom Cobb
description: Specify step and flyscan paths in a serializable, efficient and Pythonic
    way
distribution_name: scanspec
docker: true
docs_type: sphinx
git_platform: github.com
github_org: bluesky
package_name: scanspec
pypi: true
repo_name: scanspec
type_checker: pyright
