language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - env
  - pip install coveralls
  - pipenv install -v --dev
  - ls -al ${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages
  - ls -al ${VIRTUAL_ENV}/bin
  - python setup.py bdist_wheel

script:
  - pipenv run tests
  - pipenv run docs

after_script:
  - coveralls
