on:
  workflow_call:
    inputs:
      python-version:
        type: string
        description: The version of python to install, default is from .python-version file
        default: ""
      runs-on:
        type: string
        description: The runner to run this job on
        required: true
    secrets:
      CODECOV_TOKEN:
        required: true

env:
  # https://github.com/pytest-dev/pytest/issues/2042
  PY_IGNORE_IMPORTMISMATCH: "1"
  UV_PYTHON: ${{ inputs.python-version }}

jobs:
  run:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run tests
        run: uv run --locked tox -e tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          name: ${{ inputs.python-version }}/${{ inputs.runs-on }}
          files: cov.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
