name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7', '3.8' ]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          # require all of history to see all tagged versions' docs
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          env
          pip install pipenv
          pipenv install --dev
          pipenv graph

      - name: Create Sdist and Wheel
        # for reproducible builds set SOURCE_DATE_EPOCH to the date of the last commit
        # See here for more info : https://reproducible-builds.org/
        # Also use the same version of wheel as inside DLS
        run: |
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          pip install "wheel==0.33.1"
          python setup.py sdist bdist_wheel

      - name: Run Tests
        run : pipenv run tests | tee tests.out

      - name: Deploy gh-pages index.html redirect
        # Only create branch once
        if: matrix.python-version == '3.7'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/pages
          keep_files: true

      - name: Checkout gh-pages
        # Only checkout gh-pages once
        if: matrix.python-version == '3.7'
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: build/gh-pages

      - name: Build Docs and Coverage Badge
        # Only build the docs once
        if: matrix.python-version == '3.7'
        run: |
          .github/workflows/coverage.sh tests.out build/gh-pages/coverage.svg
          pipenv run sphinx-multiversion docs build/gh-pages --log-level info

      - name: Push gh-pages
        # Only push docs once from master
        if: matrix.python-version == '3.7' && github.base_ref == 'master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/gh-pages
          keep_files: true

      - name: Publish to PyPI
        # Only publish to PyPI once when a tag is pushed
        if: matrix.python-version == '3.7' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
