name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7', '3.8' ]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          # require all of history to see all tagged versions' docs
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          env
          pip install pipenv
          pipenv install --dev
          pipenv graph
          sudo apt-get install graphviz

      - name: Create Sdist and Wheel
        # for reproducible builds set SOURCE_DATE_EPOCH to the date of the last commit
        # See here for more info : https://reproducible-builds.org/
        # Also use the same version of wheel as inside DLS
        run: |
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          pip install "wheel==0.33.1"
          python setup.py sdist bdist_wheel

      - name: Run Tests
        run : |
          pipenv run tests | tee tests.out
          .github/workflows/coverage.sh tests.out .github/pages/coverage.svg

      - name: Deploy gh-pages index.html and badge
        # Only once from master
        if: matrix.python-version == '3.7' && github.ref == 'refs/heads/master'
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/pages
          keep_files: true

      - name: Publish Sdist and Wheel to PyPI
        # Only once when on a tag
        if: matrix.python-version == '3.7' && startsWith(github.ref, 'refs/tags')
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: pypa/gh-action-pypi-publish@54b39fb9371c0b3a6f9f14bb8a67394defc7a806  # v1.4.1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}

      - name: Checkout gh-pages
        if: matrix.python-version == '3.7'
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: build/html

      - name: Build Docs
        if: matrix.python-version == '3.7'
        # Use the args we normally pass to sphinx-build, but run sphinx-multiversion
        run: |
          mv $(pipenv --venv)/bin/sphinx-multiversion $(pipenv --venv)/bin/sphinx-build
          pipenv run docs

      - name: Publish Docs to gh-pages
        # Only once from master
        if: matrix.python-version == '3.7' && github.ref == 'refs/heads/master'
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
          keep_files: true
