
name: Delete gh-pages for deleted branches

# Runs your workflow anytime someone deletes a `branch` or `tag`, which triggers the `delete` event.
on:
  delete

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Delete the directory
        run: ls && echo rm ${{ github.ref }}
